name: TrippyAlpapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #font ve iconlar
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.1.0
  #bottom bar
  curved_navigation_bar: ^1.0.3

  #Login ve uygulama dataları
  shared_preferences: ^2.2.0

  #maps
  google_maps_flutter: ^2.4.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/welcome/
    - assets/search/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
